module.exports = {
  projects: [
    '<rootDir>/apps/ovb/mobile',
    '<rootDir>/libs/core/shared',
    '<rootDir>/libs/core/mobile',
    '<rootDir>/libs/base/core',
    '<rootDir>/libs/base/firebase',
    '<rootDir>/libs/learning/core',
    '<rootDir>/apps/si/web',
    '<rootDir>/libs/base/web',
    '<rootDir>/apps/ibu/web',
    '<rootDir>/apps/ovb/web',
    '<rootDir>/libs/base/translations',
    '<rootDir>/libs/access-request',
    '<rootDir>/libs/editors/form-editor',
    '<rootDir>/libs/theming/theme',
    '<rootDir>/libs/modules/country-icons',
    '<rootDir>/libs/kanban',
  ],
};
